### ISSUE TITLE
With (#) hash that EnsureAuthMiddleware authentication is not working properly

### ISSUE THREAD

**Issue by saravanans55** [HoVvo/Flutter-GetX-Rooting-Middleware#1]
I'm working for web based flutter project, So i need a proper UI routing.
When I hit the url without hash (#) it's working fine. But when i hit the url with # that EnsureAuthMiddleware not working.
Example: 1
http://localhost:53232/home ----> http://localhost:53232/#/auth (Working fine)
Example: 2
http://localhost:53232/#/home----> http://localhost:53232/#/home (Not redirecting to auth page)

Can you please figure out this issue?

**Comment by HoVvo** [comment]
Hi @saravanans55,
Can you please tell me how you’re removing hash from URL ? Are you using .htaccess or plugins ?

**Comment by saravanans55** [comment]
Thanks for the reply @HoVvo 

First I tried without adding any plugins and not removed hash from the url, It's not worked out.
2nd time I used "url_strategy" to removed the hash from the url, But also facing the same problem. 

After that I found something from the code, I put a console log inside the middleware class, the log is not showing.

FYR, Below mentioned console logs are not printing.

```
class AuthMiddleware extends GetMiddleware {

  @override
  int? get priority => 1;

  @override
  Future<GetNavConfig?> redirectDelegate(GetNavConfig route) async {
    print("AuthMiddleware----------------------userObj1");

    var _prefs = await SharedPreferences.getInstance();
    var _saved = _prefs.getString("userObj");
    log("AuthMiddleware----------------------userObj2");
    log(_saved);
    if (_saved != null) {
      final newRoute = AppPages.LOGIN_THEN(route.location!);
      return GetNavConfig.fromRoute(newRoute);
    }
    return await super.redirectDelegate(route);
  }
}

class NotAuthedMiddleware extends GetMiddleware {

  @override
  int? get priority => 1;

  @override
  Future<GetNavConfig?> redirectDelegate(GetNavConfig route) async {
    print("NotAuthedMiddleware----------------------userObj1");

    var _prefs = await SharedPreferences.getInstance();
    var _saved = _prefs.getString("userObj");
    log("NotAuthedMiddleware----------------------userObj2");
    log(_saved);
    if (_saved == null) {
      //NEVER navigate to auth screen, when user is already authed
      return null;
    }
    return await super.redirectDelegate(route);
  }
}
```

**Comment by saravanans55** [comment]
I found the mistakes, There are two mistakes.
1. I didn't write separate state for the main.dart. Instead of that, I directly used GetMaterialApp() inside of runApp. After I get reference from your sample code and write it separately. 
2. There is simple logic mistake in if condition. Now it's working perfectly. Now, when the user having the session now it will not redirect to login page.
